import Image from 'next/image'
import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'note',
    description: 'Generated by create next app',
  }

export default function Note() {
  return (
    <main>
      <h1>Note</h1>
    </main>
  )
}
